language: python
python: 
  - "3.5"
install: "pip install django"
notifications:
  email: false
deploy:
  - provider: script
    script: staging.sh
    on:
      branch: staging
  - provider: script
    script: production.sh
    on:
      branch: master