language: python
python: 
  - "3.5"
install: "pip install django"
script: python -m unittest test.py
notifications:
  email: false
deploy:
  - provider: script
    skip_cleanup: true
    script: echo 'Deployed to Staging Server'
    on:
      branch: staging
  - provider: script
    skip_cleanup: true
    script: echo 'Deployed to Production Server'
    on:
      branch: master